---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.6.2

platforms:
  - name: ubuntu-14.04-i386

suites:
  - name: celery
    run_list:
      - recipe[celery_test::default]
    attributes:
